export default function Layout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Twitter But Better</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>{children}</body>
    </html>
  );
}
